#!name=Keep
#!desc=Keep解锁会员
#!homepage=https://github.com/deezertidal
#!author=89996462
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/keep.png
#!url=https://raw.githubusercontent.com/ligengying/123/master/module/keep.module

[Script]
keep=type=http-response,pattern=^https:\/\/api\.gotokeep\.com,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/keep.js
[MITM] 
hostname = %APPEND% api.gotokeep.com
