#!name=人人视频
#!desc=人人视频解锁会员
#https://raw.githubusercontent.com/ligengying/123/master/module/rrsp.module

[Script]
rrsp=type=http-response,pattern=^http[s]?:\/\/api\.qwapp\.top\/user\/personal\/information,requires-body=1,script-path=https://raw.githubusercontent.com/ligengying/123/master/script/rrspvip.js
rrsp=type=http-response,pattern=^http[s]?:\/\/api\.qwapp\.top\/app\/drama\/page,requires-body=1,script-path=https://raw.githubusercontent.com/ligengying/123/master/script/rrspvip1.js


[MITM]
hostname = %APPEND% api.qwapp.top